{
    "swagger": "2.0",
    "info": {
        "title": "\u5168\u56fd\u5144\u5f1f\u60c5\u7cbe\u9009\u8f66 API\u63a5\u53e3",
        "description": "\u5168\u56fd\u5144\u5f1f\u60c5\u7cbe\u9009\u8f66API\u63a5\u53e3\uff0c\u7528\u4e8e\u524d\u7aef\u5c0f\u7a0b\u5e8f\u8c03\u7528\u3002",
        "termsOfService": "#",
        "contact": {
            "email": "daniel_c_tao@qq.com"
        },
        "license": {
            "name": "PHP 7.2 & ThinkPHP 5.1.27",
            "url": "#"
        },
        "version": "1.0"
    },
    "host": "che.xingyizxmr.com:8080",
    "basePath": "",
    "schemes": [
        "http"
    ],
    "paths": {
        "/api/areas/getprovince": {
            "get": {
                "tags": [
                    "5-\u5730\u533a\u90e8\u5206\u63a5\u53e3"
                ],
                "summary": "4.1-\u83b7\u53d6\u7701\u4efd\u4fe1\u606f",
                "description": "\u83b7\u53d6\u7701\u4efd\u4fe1\u606f(\u4e3a\u5c0f\u7a0b\u5e8f\u4f7f\u7528)",
                "operationId": "getprovince",
                "security": [
                    {
                        "petstore_auth": [
                            "write:getprovince",
                            "read:getprovince"
                        ]
                    }
                ]
            }
        },
        "/api/areas/getcity?proviceid=110000": {
            "get": {
                "tags": [
                    "5-\u5730\u533a\u90e8\u5206\u63a5\u53e3"
                ],
                "summary": "4.2-\u6839\u636e\u7701id\u83b7\u53d6\u5e02\u4fe1\u606f",
                "description": "\u83b7\u53d6\u5e02\u4fe1\u606f(\u4e3a\u5c0f\u7a0b\u5e8f\u4f7f\u7528)",
                "operationId": "getcity",
                "security": [
                    {
                        "petstore_auth": [
                            "write:getcity",
                            "read:getcity"
                        ]
                    }
                ]
            }
        },
        "/api/areas/getarea?cityid=110900": {
            "get": {
                "tags": [
                    "5-\u5730\u533a\u90e8\u5206\u63a5\u53e3"
                ],
                "summary": "4.3-\u6839\u636e\u5e02id\u83b7\u53d6\u5730\u533a\u4fe1\u606f",
                "description": "\u83b7\u53d6\u5730\u533a\u4fe1\u606f(\u4e3a\u5c0f\u7a0b\u5e8f\u4f7f\u7528)",
                "operationId": "getarea",
                "security": [
                    {
                        "petstore_auth": [
                            "write:getarea",
                            "read:getarea"
                        ]
                    }
                ]
            }
        },
        "/api/Config/info": {
            "get": {
                "tags": [
                    "2-\u7cfb\u7edf\u914d\u7f6e\u7ba1\u7406\u90e8\u5206\u63a5\u53e3"
                ],
                "summary": "2.1-\u83b7\u53d6\u7cfb\u7edf\u914d\u7f6e\u4fe1\u606f",
                "description": "\u83b7\u53d6\u7cfb\u7edf\u914d\u7f6e\u4fe1\u606f(\u4e3a\u5c0f\u7a0b\u5e8f\u4f7f\u7528)\u3002\u83b7\u53d6\u7cfb\u7edf\u5e7f\u544a\u4f4d\uff0c\u5fae\u4fe1\u4e8c\u7ef4\u7801\uff0c\u624b\u673a\u53f7\uff0c\u8054\u7cfb\u65b9\u5f0f\u3002",
                "operationId": "info",
                "security": [
                    {
                        "petstore_auth": [
                            "write:info",
                            "read:info"
                        ]
                    }
                ]
            }
        },
        "/api/Upload/uploadimg": {
            "post": {
                "tags": [
                    "4-\u4e0a\u4f20\u56fe\u7247\u63a5\u53e3"
                ],
                "summary": "4.1-\u6dfb\u52a0\u56fe\u7247",
                "description": "\u6dfb\u52a0\u56fe\u7247(\u540e\u53f0\u4f7f\u7528)\u3002",
                "operationId": "uploadimg",
                "security": [
                    {
                        "petstore_auth": [
                            "write:uploadimg",
                            "read:uploadimg"
                        ]
                    }
                ]
            }
        },
        "/api/Upload/upload": {
            "post": {
                "tags": [
                    "4-\u4e0a\u4f20\u56fe\u7247\u63a5\u53e3"
                ],
                "summary": "4.2-\u6dfb\u52a0\u56fe\u7247",
                "description": "\u6dfb\u52a0\u56fe\u7247(\u4e3a\u5c0f\u7a0b\u5e8f\u4f7f\u7528)\u3002",
                "operationId": "upload",
                "security": [
                    {
                        "petstore_auth": [
                            "write:upload",
                            "read:upload"
                        ]
                    }
                ]
            }
        },
        "/api/User/add": {
            "post": {
                "tags": [
                    "1-\u7528\u6237\u7ba1\u7406\u90e8\u5206\u63a5\u53e3"
                ],
                "summary": "1.1-\u6dfb\u52a0\u7528\u6237",
                "description": "\u6dfb\u52a0\u7528\u6237(\u4e3a\u5c0f\u7a0b\u5e8f\u4f7f\u7528)\u3002",
                "operationId": "add",
                "security": [
                    {
                        "petstore_auth": [
                            "write:add",
                            "read:add"
                        ]
                    }
                ]
            }
        },
        "/api/User/info?openid={openid}&mobileno={mobileno}": {
            "get": {
                "tags": [
                    "1-\u7528\u6237\u7ba1\u7406\u90e8\u5206\u63a5\u53e3"
                ],
                "summary": "1.2-\u83b7\u53d6\u7528\u6237\u4fe1\u606f",
                "description": "\u83b7\u53d6\u7528\u6237\u4fe1\u606f(\u4e3a\u5c0f\u7a0b\u5e8f\u4f7f\u7528)\u3002openid\u548cmobileno\u4e24\u8005\u4f20\u4e00\u4e2a\u5373\u53ef\u3002",
                "operationId": "info",
                "security": [
                    {
                        "petstore_auth": [
                            "write:info",
                            "read:info"
                        ]
                    }
                ]
            }
        },
        "/api/User/loginWxxcx?code={code}&encryptedData={encryptedData}&iv={iv}": {
            "get": {
                "tags": [
                    "1-\u7528\u6237\u7ba1\u7406\u90e8\u5206\u63a5\u53e3"
                ],
                "summary": "1.3-\u83b7\u53d6\u7528\u6237\u4fe1\u606f",
                "description": "\u83b7\u53d6\u7528\u6237\u4fe1\u606f(\u4e3a\u5c0f\u7a0b\u5e8f\u4f7f\u7528)\u3002code\\encryptedData\\iv\u3002",
                "operationId": "loginWxxcx",
                "security": [
                    {
                        "petstore_auth": [
                            "write:loginWxxcx",
                            "read:loginWxxcx"
                        ]
                    }
                ]
            }
        },
        "/api/vehicle/getonevehicleinfo?id={id}&openid={openid}": {
            "get": {
                "tags": [
                    "3-\u8f66\u8f86\u7ba1\u7406\u90e8\u5206\u63a5\u53e3"
                ],
                "summary": "3.2-\u83b7\u53d6\u8f66\u8f86\u4fe1\u606f",
                "description": "\u83b7\u53d6\u8f66\u8f86\u4fe1\u606f(\u4e3a\u5c0f\u7a0b\u5e8f\u4f7f\u7528)\u3002\u53ef\u53ea\u4f20\u4e00\u4e2a\u53c2\u6570id\uff0c\u83b7\u53d6\u6211\u53d1\u5e03\u7684\u8f66\u8f86\u4e5f\u662f\u5728\u8fd9\u91cc",
                "operationId": "getvehicleinfo",
                "security": [
                    {
                        "petstore_auth": [
                            "write:getonevehicleinfo",
                            "read:getonevehicleinfo"
                        ]
                    }
                ]
            }
        },
        "/api/vehicle/getvehicleinfo?openid={openid}&pricefrom={pricefrom}&priceto={priceto}&timefrom={timefrom}&timeto={timeto}&models={models}&self=1": {
            "get": {
                "tags": [
                    "3-\u8f66\u8f86\u7ba1\u7406\u90e8\u5206\u63a5\u53e3"
                ],
                "summary": "3.3-\u83b7\u53d6\u8f66\u8f86\u4fe1\u606f",
                "description": "\u83b7\u53d6\u8f66\u8f86\u4fe1\u606f(\u4e3a\u5c0f\u7a0b\u5e8f\u4f7f\u7528)\u3002\u53ef\u53ea\u4f20\u4e00\u4e2a\u53c2\u6570\uff0c\u83b7\u53d6\u6211\u53d1\u5e03\u7684\u8f66\u8f86\u4e5f\u662f\u5728\u8fd9\u91cc",
                "operationId": "getvehicleinfo",
                "security": [
                    {
                        "petstore_auth": [
                            "write:getvehicleinfo",
                            "read:getvehicleinfo"
                        ]
                    }
                ]
            }
        },
        "/api/vehicle/updatestatus?id={id}&status={status}": {
            "get": {
                "tags": [
                    "3-\u8f66\u8f86\u7ba1\u7406\u90e8\u5206\u63a5\u53e3"
                ],
                "summary": "3.3-\u66f4\u65b0\u8f66\u8f86\u72b6\u6001",
                "description": "\u66f4\u65b0\u8f66\u8f86\u72b6\u6001\u3002\u66f4\u65b0\u8f66\u8f86\u72b6\u6001,status=2\u662f\u5ba1\u6838\u901a\u8fc7 status=3\u662f\u5ba1\u6838\u4e0d\u901a\u8fc7",
                "operationId": "updatestatus",
                "security": [
                    {
                        "petstore_auth": [
                            "write:updatestatus",
                            "read:updatestatus"
                        ]
                    }
                ]
            }
        }
    }
}